[flaskservers]
#3.90.3.245 ansible_user=ubuntu ansible_ssh_private_key_file=./pradeep.pem
#52.204.50.225 ansible_user=ec2-user ansible_ssh_private_key_file=./playbooks/pradeep.pem
#54.234.134.95 ansible_user=ec2-user ansible_ssh_private_key_file=./playbooks/pradeep.pem
3.236.238.250 ansible_user=ec2-user ansible_ssh_private_key_file=./playbooks/pradeep.pem
